services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/auth:/mosquitto/config/auth
      - ./config/certs:/mosquitto/config/certs
      - ./logs:/mosquitto/log
    ports:
      - "8883:8883"
    environment:
      - TZ=EST
    cap_add:
      - NET_ADMIN
      - NET_RAW

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/certs:/etc/nginx/ssl
    ports:
      - "443:443"
    depends_on:
      - mosquitto
    cap_add:
      - NET_ADMIN
      - NET_RAW

  firewall:
      image: alpine
      volumes:
        - firewall.sh:/firewall.sh
      # Ensure firewall runs on all services
      network_mode: "host"
      privileged: true
      cap_add:
        - NET_ADMIN
        - NET_RAW
      command: sh -c "
        chmod +x /firewall.sh && 
        apk add --no-cache iptables && 
        /firewall.sh"
      restart: always