services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/auth:/mosquitto/config/auth
      - ./config/certs:/mosquitto/config/certs
      - ./logs:/mosquitto/log
    ports:
      - 8883:8883
    environment:
      - TZ=EST
    networks:
      - mosquitto_network
    restart: always


  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/certs:/etc/nginx/ssl
      - ./logs:/etc/nginx/log
    ports:
      - 443:443
    depends_on:
      - mosquitto
    networks:
      - mosquitto_network
    restart: always

  # firewall:
  #   image: ubuntu:latest
  #   volumes:
  #     - ./firewall.sh:/bin/firewall.sh
  #   network_mode: "host"  # Gives the container direct access to the host's network
  #   privileged: true      # Required for modifying iptables
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   entrypoint: ["/bin/bash", "/bin/firewall.sh"]  # Run the firewall script on startup
  #   restart: always

networks:
  mosquitto_network:
    driver: bridge
